app_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docs_pdf.urls')),
]

docs_pdf/urls.py
from django.urls import path
from . import views

app_name = 'docs_pdf'


urlpatterns = [
    path('', views.convertir_word_pdf, name='convertir_word_pdf'),
    path('descargar-pdf/<str:filename>/', views.descargar_pdf, name='descargar_pdf'),
]

docs_pdf/models.py
from django.db import models

# Create your models here.

docs_pdf/views.py
import os
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from docx2pdf import convert
from django.conf import settings

def convertir_word_pdf(request):
    message = None
    archivo_pdf = None
    
    if request.method == 'POST' and request.FILES.get('word_file'):
        word_file = request.FILES['word_file']
        
        # Definir el almacenamiento en la carpeta MEDIA_ROOT/pdf_files
        upload_dir = os.path.join(settings.MEDIA_ROOT, 'pdf_files')
        os.makedirs(upload_dir, exist_ok=True)  # Asegurar que la carpeta existe
        fs = FileSystemStorage(location=upload_dir)

        # Guardar el archivo en la carpeta definida
        filename = fs.save(word_file.name, word_file)
        filepath = os.path.join(upload_dir, filename)

        # Definir la ruta del archivo PDF
        pdf_filename = os.path.splitext(filename)[0] + '.pdf'
        pdf_path = os.path.join(upload_dir, pdf_filename)

        try:
            # Realizar la conversión
            convert(filepath, pdf_path)
            
            # Eliminar el archivo Word después de la conversión
            os.remove(filepath)

            archivo_pdf = pdf_filename
            message = f"¡Se ha convertido {word_file.name} a {archivo_pdf} exitosamente!"
        except Exception as e:
            message = f"Ocurrió un error al convertir el archivo: {str(e)}"

    return render(request, 'index.html', {'message': message, 'archivo_pdf': archivo_pdf})

def descargar_pdf(request, filename):
    pdf_path = os.path.join(settings.MEDIA_ROOT, 'pdf_files', filename)

    if os.path.exists(pdf_path):
        with open(pdf_path, 'rb') as pdf:
            response = HttpResponse(pdf.read(), content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="{filename}"'
            return response
    else:
        return HttpResponseNotFound('El archivo PDF no se encontró')

docs_pdf/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Convertir Word a PDF</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


</head>
<body>
    <header>
        <h1>Convertir Word a PDF</h1>
    </header>

    <main>
        <form id="conversion_form" action="{% url 'docs_pdf:convertir_word_pdf' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="word_file">Seleccionar archivo Word:</label><br>
            <input type="file" id="word_file" name="word_file" required><br><br>
            <button type="submit">Convertir a PDF</button>
        </form>

        {% if message %}
            <div id="result_message" class="{% if 'error' in message.lower %}error{% else %}success{% endif %}">{{ message }}</div>
        {% endif %}

        {% if archivo_pdf %}
            <a href="{% url 'docs_pdf:descargar_pdf' filename=archivo_pdf %}" id="download_link">Descargar PDF</a>
        {% endif %}
    </main>
    <footer>
        <p>&copy; 2024 Best Doit</p>
           <a href="https://www.tiktok.com/@best_doit" target="_blank"><i class="fab fa-tiktok" id="icono-redes"></i></a>
    </footer>
</body>
</html>